apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: configuration-aws-foundation
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
    version: '>=v1.2.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Configuration
    package: ghcr.io/hops-ops/configuration-aws-organization
    version: '>=v0.13.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Configuration
    package: ghcr.io/hops-ops/configuration-aws-identity-center
    version: '>=v0.3.2'
  - apiVersion: pkg.crossplane.io/v1
    kind: Configuration
    package: ghcr.io/hops-ops/configuration-aws-ipam
    version: '>=v0.11.0'
  description: |
    Foundation XRD - A unified API for creating the complete AWS foundational layer.
    Composes Organization, IdentityCenter, and IPAM XRDs with automatic account ID
    resolution and ProviderConfig creation for cross-account access.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # configuration-aws-foundation

    Foundation creates a complete AWS foundation in a single resource by composing:
    - **Organization XRD** - AWS Organization with OUs and accounts
    - **IdentityCenter XRD** - Groups, users, permission sets, account assignments
    - **IPAM XRD** - IP pools for VPC management with RAM sharing

    Key features:
    - Account names can be referenced everywhere and are automatically resolved to AWS account IDs
    - OU paths are automatically resolved for IPAM RAM sharing
    - Each account gets a ProviderConfig using OrganizationAccountAccessRole

    Example:
    ```yaml
    apiVersion: aws.hops.ops.com.ai/v1alpha1
    kind: Foundation
    metadata:
      name: acme
    spec:
      accounts:
        - name: shared-services
          email: shared@example.com
          ou: Infrastructure
      delegatedAdministrators:
        - servicePrincipal: ipam.amazonaws.com
          account: shared-services  # Reference by name!
      ipam:
        delegatedAdminAccount: shared-services  # Reference by name!
        pools:
          - name: prod-vpc
            cidr: 10.0.0.0/16
            ramShareTargets:
              - ou: Workloads/Prod  # Reference by path!
    ```
  repository: ghcr.io/hops-ops/configuration-aws-foundation
  source: github.com/hops-ops/configuration-aws-foundation
