# Enterprise: Production-grade AWS foundation
# ============================================
# Complete multi-account architecture following AWS best practices:
# - OU hierarchy for security, infrastructure, and workloads
# - Dedicated accounts for security tooling and shared services
# - Identity Center with groups and permission sets
# - IPAM with hierarchical pools (global → regional → environment)
# - VPC networks in each account with consistent layouts
# - Cross-account access with permission boundaries
#
# This example creates:
# - 1 AWS Organization
# - 6 Organizational Units (hierarchical)
# - 5 Member Accounts
# - 2 Delegated Administrators (SSO, IPAM)
# - 3 Identity Store Groups
# - 3 Permission Sets with account assignments
# - IPAM with multi-region hierarchical IPv4 and IPv6 pools
# - VPCs in prod, staging, dev, and shared-services accounts
#
# After apply, each account has a ProviderConfig ready:
#   providerConfigRef:
#     name: acme-prod  # or acme-dev, acme-shared-services, etc.

apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Foundation
metadata:
  name: acme
  namespace: acme
spec:
  managementPolicies: ["*"]

  aws:
    providerConfig: aws-management-account
    region: us-east-1

  tags:
    organization: acme
    environment: production
    managed-by: crossplane

  # ---------------------------------------------------------------------------
  # Organization Settings
  # ---------------------------------------------------------------------------
  organization:
    awsServiceAccessPrincipals:
      - sso.amazonaws.com
      - ipam.amazonaws.com
      - ram.amazonaws.com

  # ---------------------------------------------------------------------------
  # Organizational Unit Hierarchy
  # ---------------------------------------------------------------------------
  # AWS best-practice structure:
  # Root
  # ├── Security          (security tooling, log archive, audit)
  # ├── Infrastructure    (shared services, networking, CI/CD)
  # ├── Workloads
  # │   ├── Prod          (production workloads)
  # │   └── Non-Prod      (staging, dev, QA)
  # └── Sandbox           (experimentation, learning)

  organizationalUnits:
    - path: Security
    - path: Infrastructure
    - path: Workloads
    - path: Workloads/Prod
    - path: Workloads/Non-Prod
    - path: Sandbox

  # ---------------------------------------------------------------------------
  # Accounts
  # ---------------------------------------------------------------------------
  # Each account gets:
  # - cross-account-access role (AdministratorAccess by default)
  # - Permission boundary (prevents access key creation, etc.)
  # - ProviderConfig for downstream resource management

  accounts:
    # Security OU
    - name: acme-security-tooling
      email: security-tooling@acme.example.com
      ou: Security
      tags:
        team: security

    # Infrastructure OU
    - name: acme-shared-services
      email: shared-services@acme.example.com
      ou: Infrastructure
      tags:
        team: platform

    # Production workloads
    - name: acme-prod
      email: prod@acme.example.com
      ou: Workloads/Prod
      tags:
        environment: production

    # Non-production workloads
    - name: acme-staging
      email: staging@acme.example.com
      ou: Workloads/Non-Prod
      tags:
        environment: staging

    - name: acme-dev
      email: dev@acme.example.com
      ou: Workloads/Non-Prod
      tags:
        environment: development

  # ---------------------------------------------------------------------------
  # Delegated Administrators
  # ---------------------------------------------------------------------------
  # Delegate AWS service administration to shared-services account

  delegatedAdministrators:
    - servicePrincipal: sso.amazonaws.com
      account: acme-shared-services
    - servicePrincipal: ipam.amazonaws.com
      account: acme-shared-services

  # ---------------------------------------------------------------------------
  # Identity Center
  # ---------------------------------------------------------------------------
  # Centralized access management with SSO

  identityCenter:
    region: us-east-1
    identityStoreId: d-1234567890        # From AWS SSO console
    instanceArn: arn:aws:sso:::instance/ssoins-abcdef0123456789

    # Groups for access control
    groups:
      - name: Administrators
        description: Full administrative access to all accounts

      - name: Developers
        description: Development access to non-production accounts

      - name: ReadOnly
        description: Read-only access for auditing and compliance

    # Permission sets define what access each group gets
    permissionSets:
      - name: AdministratorAccess
        description: Full administrator access
        sessionDuration: PT4H
        managedPolicies:
          - arn:aws:iam::aws:policy/AdministratorAccess
        assignToGroups:
          - Administrators
        assignToAccounts:
          - acme-shared-services
          - acme-security-tooling
          - acme-prod
          - acme-staging
          - acme-dev

      - name: DeveloperAccess
        description: Developer access for non-prod environments
        sessionDuration: PT8H
        managedPolicies:
          - arn:aws:iam::aws:policy/PowerUserAccess
        assignToGroups:
          - Developers
        assignToAccounts:
          - acme-staging
          - acme-dev

      - name: ViewOnlyAccess
        description: Read-only access for compliance review
        sessionDuration: PT1H
        managedPolicies:
          - arn:aws:iam::aws:policy/ViewOnlyAccess
        assignToGroups:
          - ReadOnly
        assignToAccounts:
          - acme-shared-services
          - acme-security-tooling
          - acme-prod
          - acme-staging
          - acme-dev

  # ---------------------------------------------------------------------------
  # IPAM - Multi-Region Hierarchical Dual-Stack Configuration
  # ---------------------------------------------------------------------------
  # IP Address Manager with global → regional → environment pool hierarchy.
  # Pools are shared via RAM to appropriate OUs/accounts.
  #
  # IPv4 Pool Hierarchy:
  #   ipv4-global (10.0.0.0/8)
  #   ├── ipv4-us-east-1 (10.0.0.0/10)
  #   │   ├── ipv4-us-east-1-prod (10.0.0.0/12) → Workloads/Prod OU
  #   │   ├── ipv4-us-east-1-nonprod (10.16.0.0/12) → Workloads/Non-Prod OU
  #   │   └── ipv4-us-east-1-shared (10.32.0.0/16) → shared-services account
  #   └── ipv4-us-west-2 (10.64.0.0/10)
  #       └── ipv4-us-west-2-prod (10.64.0.0/12) → Workloads/Prod OU (DR)
  #
  # IPv6 ULA Pool Hierarchy:
  #   ipv6-ula-global (/40)
  #   ├── ipv6-ula-us-east-1 (/44) → Workloads OU
  #   └── ipv6-ula-us-west-2 (/44) → Workloads OU
  #
  # IPv6 GUA Pools (Amazon-provided, no hierarchy):
  #   ipv6-gua-us-east-1 (/52) → Workloads OU
  #   ipv6-gua-us-west-2 (/52) → Workloads OU

  ipam:
    delegatedAdminAccount: acme-shared-services
    region: us-east-1
    operatingRegions:
      - us-east-1
      - us-west-2

    pools:
      # ==========================================================================
      # IPv4 Pools - Global → Regional → Environment hierarchy
      # ==========================================================================
      ipv4:
        # Global pool - top of hierarchy
        - name: ipv4-global
          cidr: 10.0.0.0/8
          allocations:
            netmaskLength:
              default: 10  # Carve /10 per region
          description: Global IPv4 pool

        # --- us-east-1 regional pools ---
        - name: ipv4-us-east-1
          sourcePoolRef: ipv4-global
          locale: us-east-1
          cidr: 10.0.0.0/10      # 10.0.0.0 - 10.63.255.255
          allocations:
            netmaskLength:
              default: 12
          description: Regional IPv4 pool for us-east-1

        # Production pool - shared with Workloads/Prod OU
        - name: ipv4-us-east-1-prod
          sourcePoolRef: ipv4-us-east-1
          locale: us-east-1
          cidr: 10.0.0.0/12      # 10.0.0.0 - 10.15.255.255
          allocations:
            netmaskLength:
              default: 16
              min: 16
              max: 24
          ramShareTargets:
            - ou: Workloads/Prod
          description: Production IPv4 pool for us-east-1
          labels:
            environment: production
            region: us-east-1

        # Non-prod pool - shared with Workloads/Non-Prod OU
        - name: ipv4-us-east-1-nonprod
          sourcePoolRef: ipv4-us-east-1
          locale: us-east-1
          cidr: 10.16.0.0/12     # 10.16.0.0 - 10.31.255.255
          allocations:
            netmaskLength:
              default: 16
              min: 16
              max: 24
          ramShareTargets:
            - ou: Workloads/Non-Prod
          description: Non-production IPv4 pool for us-east-1
          labels:
            environment: non-production
            region: us-east-1

        # Shared services pool
        - name: ipv4-us-east-1-shared
          sourcePoolRef: ipv4-us-east-1
          locale: us-east-1
          cidr: 10.32.0.0/16     # 10.32.0.0 - 10.32.255.255
          allocations:
            netmaskLength:
              default: 20
              min: 20
              max: 24
          ramShareTargets:
            - account: acme-shared-services
          description: Shared services IPv4 pool
          labels:
            environment: shared
            region: us-east-1

        # --- us-west-2 regional pools (DR/multi-region) ---
        - name: ipv4-us-west-2
          sourcePoolRef: ipv4-global
          locale: us-west-2
          cidr: 10.64.0.0/10     # 10.64.0.0 - 10.127.255.255
          allocations:
            netmaskLength:
              default: 12
          description: Regional IPv4 pool for us-west-2

        - name: ipv4-us-west-2-prod
          sourcePoolRef: ipv4-us-west-2
          locale: us-west-2
          cidr: 10.64.0.0/12
          allocations:
            netmaskLength:
              default: 16
              min: 16
              max: 24
          ramShareTargets:
            - ou: Workloads/Prod
          description: Production IPv4 pool for us-west-2 (DR)
          labels:
            environment: production
            region: us-west-2

      # ==========================================================================
      # IPv6 Pools - ULA (private) and GUA (public)
      # ==========================================================================
      ipv6:
        # ULA pools - Private IPv6 (fd00::/8), not internet-routable
        ula:
          # Global ULA pool
          - name: ipv6-ula-global
            netmaskLength: 40
            allocations:
              netmaskLength:
                default: 44
            description: Global ULA IPv6 pool

          # Regional ULA - us-east-1
          - name: ipv6-ula-us-east-1
            sourcePoolRef: ipv6-ula-global
            locale: us-east-1
            netmaskLength: 44
            allocations:
              netmaskLength:
                default: 48
                min: 48
                max: 56
            ramShareTargets:
              - ou: Workloads
            description: Regional ULA IPv6 for us-east-1
            labels:
              region: us-east-1

          # Regional ULA - us-west-2
          - name: ipv6-ula-us-west-2
            sourcePoolRef: ipv6-ula-global
            locale: us-west-2
            netmaskLength: 44
            allocations:
              netmaskLength:
                default: 48
                min: 48
                max: 56
            ramShareTargets:
              - ou: Workloads
            description: Regional ULA IPv6 for us-west-2
            labels:
              region: us-west-2

        # GUA pools - Amazon-provided public IPv6
        gua:
          - name: ipv6-gua-us-east-1
            locale: us-east-1
            netmaskLength: 52
            publicIpSource: amazon
            awsService: ec2
            allocations:
              netmaskLength:
                default: 56
                min: 52
                max: 60
            ramShareTargets:
              - ou: Workloads
            description: Public IPv6 pool for us-east-1 (Amazon GUA)
            labels:
              region: us-east-1
              eks-ready: "true"

          - name: ipv6-gua-us-west-2
            locale: us-west-2
            netmaskLength: 52
            publicIpSource: amazon
            awsService: ec2
            allocations:
              netmaskLength:
                default: 56
                min: 52
                max: 60
            ramShareTargets:
              - ou: Workloads
            description: Public IPv6 pool for us-west-2 (Amazon GUA)
            labels:
              region: us-west-2
              eks-ready: "true"

  # ---------------------------------------------------------------------------
  # Network Defaults
  # ---------------------------------------------------------------------------
  # These settings are inherited by all networks unless overridden.
  networkDefaults:
    subnetLayout:
      availabilityZones: [a, b, c]
      public:
        enabled: true
        netmaskLength: 24
      private:
        enabled: true
        netmaskLength: 20
    nat:
      enabled: true
      strategy: SingleAz

  # ---------------------------------------------------------------------------
  # Networks - VPCs in each account
  # ---------------------------------------------------------------------------
  # Each network targets a specific account and allocates from IPAM pools.
  # - `poolRef` references pools by name (Foundation resolves to pool ID)
  # - `account` targets that account's ProviderConfig
  # - Omitting `account` targets management account
  networks:
    # Production VPC - HA NAT, all 3 AZs
    - name: production
      account: acme-prod
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1-prod
          netmaskLength: 16
      nat:
        strategy: HighlyAvailable    # Override: HA for production
      tags:
        environment: production
        tier: workload

    # Staging VPC - 2 AZs for cost savings
    - name: staging
      account: acme-staging
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1-nonprod
          netmaskLength: 16
      subnetLayout:
        availabilityZones: [a, b]    # Override: only 2 AZs
      tags:
        environment: staging
        tier: workload

    # Dev VPC - minimal, single AZ, no NAT
    - name: dev
      account: acme-dev
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1-nonprod
          netmaskLength: 18           # Smaller /18 for dev
      subnetLayout:
        availabilityZones: [a]        # Override: single AZ
        private:
          enabled: false              # Override: no private subnets
      nat:
        enabled: false                # Override: no NAT
      tags:
        environment: development
        tier: workload

    # Shared services VPC - management account, manual CIDR
    - name: shared-services
      # No account = uses management account (spec.aws.providerConfig)
      region: us-east-1
      vpc:
        cidr: "10.32.0.0/16"          # Manual CIDR (not from IPAM)
      tags:
        environment: shared
        tier: infrastructure
