# Import Existing: Adopt an existing AWS Organization and VPCs
# =============================================================
# Use this when you already have an AWS Organization and VPCs and want
# Crossplane to manage them. Resources are adopted (not created)
# and won't be deleted when the Foundation is removed.
#
# Steps to import:
# 1. Get your organization ID: aws organizations describe-organization
# 2. Get existing OU IDs: aws organizations list-organizational-units-for-parent
# 3. Get existing account IDs: aws organizations list-accounts
# 4. Get VPC/subnet/route table IDs: aws ec2 describe-vpcs, describe-subnets, etc.
# 5. Set externalName on each resource you want to adopt
#
# Management policies:
# - Organization uses Observe-only (won't delete the org)
# - OUs and accounts can use full management (will be deleted if removed)
# - Networks use Observe-only per-resource to prevent deletion
# - Adjust per-resource as needed

apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Foundation
metadata:
  name: imported-org
  namespace: default
spec:
  managementPolicies: ["*"]

  aws:
    providerConfig: aws-management
    region: us-east-1

  tags:
    managed-by: crossplane
    imported: "true"

  # ---------------------------------------------------------------------------
  # Import existing organization
  # ---------------------------------------------------------------------------
  organization:
    externalName: o-abc123xyz  # Your existing organization ID
    # Don't delete the organization when Foundation is removed
    managementPolicies:
      - Create
      - Observe
      - Update
      - LateInitialize

  # ---------------------------------------------------------------------------
  # Import existing OUs
  # ---------------------------------------------------------------------------
  organizationalUnits:
    - path: Security
      externalName: ou-abc1-security12    # Existing OU ID

    - path: Infrastructure
      externalName: ou-abc1-infra1234

    - path: Workloads
      externalName: ou-abc1-workloads1

    - path: Workloads/Prod
      externalName: ou-abc1-prod12345

    - path: Workloads/Non-Prod
      externalName: ou-abc1-nonprod12

  # ---------------------------------------------------------------------------
  # Import existing accounts
  # ---------------------------------------------------------------------------
  # Existing accounts are adopted and get cross-account access configured
  accounts:
    - name: shared-services
      email: shared-services@example.com  # Must match existing
      ou: Infrastructure
      externalName: "222222222222"        # Existing account ID
      # Observe-only: don't close account if removed from config
      managementPolicies:
        - Create
        - Observe
        - Update
        - LateInitialize

    - name: production
      email: production@example.com
      ou: Workloads/Prod
      externalName: "333333333333"
      managementPolicies:
        - Create
        - Observe
        - Update
        - LateInitialize

    - name: development
      email: development@example.com
      ou: Workloads/Non-Prod
      externalName: "444444444444"
      managementPolicies:
        - Create
        - Observe
        - Update
        - LateInitialize

  # ---------------------------------------------------------------------------
  # Identity Center (optional)
  # ---------------------------------------------------------------------------
  # If you already have Identity Center set up, configure it here
  # Groups and permission sets will be created/managed by Crossplane

  identityCenter:
    region: us-east-1
    identityStoreId: d-1234567890
    instanceArn: arn:aws:sso:::instance/ssoins-abcdef

    groups:
      - name: Administrators
        description: Full admin access
        # Import existing group
        externalName: 12345678-abcd-1234-abcd-123456789012

    permissionSets:
      - name: AdministratorAccess
        managedPolicies:
          - arn:aws:iam::aws:policy/AdministratorAccess
        # Import existing permission set
        externalName: arn:aws:sso:::permissionSet/ssoins-abcdef/ps-1234567890abcdef
        assignToGroups:
          - Administrators
        assignToAccounts:
          - shared-services
          - production
          - development

  # ---------------------------------------------------------------------------
  # Import existing VPCs
  # ---------------------------------------------------------------------------
  # Each network can import existing VPC, subnets, route tables, and gateways.
  # Use direct poolId (not poolRef) when importing - the VPC already has its CIDR.
  # Get resource IDs:
  #   aws ec2 describe-vpcs
  #   aws ec2 describe-internet-gateways
  #   aws ec2 describe-subnets
  #   aws ec2 describe-route-tables
  networks:
    - name: production
      account: production
      region: us-east-1
      managementPolicies: [Observe]  # Observe-only at network level

      # Direct pool ID (VPC already allocated from this pool)
      ipam:
        ipv4:
          poolId: ipam-pool-abc123def  # Direct ID, not poolRef
          netmaskLength: 16

      # Import VPC
      vpc:
        externalName: vpc-0abc123def456789
        managementPolicies: [Observe]

      # Import Internet Gateway
      internetGateway:
        externalName: igw-0abc123def456789
        managementPolicies: [Observe]

      # Import subnets by name → ID mapping
      subnetLayout:
        availabilityZones: [a, b, c]
        public:
          enabled: true
          netmaskLength: 24
        private:
          enabled: true
          netmaskLength: 20
        externalNames:
          public-a: subnet-pub-a-123456
          public-b: subnet-pub-b-123456
          public-c: subnet-pub-c-123456
          private-a: subnet-priv-a-123456
          private-b: subnet-priv-b-123456
          private-c: subnet-priv-c-123456
        managementPolicies: [Observe]

      # Import route tables
      routeTables:
        externalNames:
          public: rtb-pub-123456
          private-a: rtb-priv-a-123456
          private-b: rtb-priv-b-123456
          private-c: rtb-priv-c-123456
        associationExternalNames:
          public-a: rtbassoc-pub-a-123456
          public-b: rtbassoc-pub-b-123456
          public-c: rtbassoc-pub-c-123456
          private-a: rtbassoc-priv-a-123456
          private-b: rtbassoc-priv-b-123456
          private-c: rtbassoc-priv-c-123456
        managementPolicies: [Observe]

      # Import NAT gateways (if you have them)
      # Get IDs: aws ec2 describe-nat-gateways
      nat:
        enabled: true
        strategy: SingleAz  # Or HighlyAvailable if you have one per AZ
        externalNames:
          a: nat-0abc123def456789
        eipExternalNames:
          a: eipalloc-0abc123def456789
        managementPolicies: [Observe]
