# Individual: Simple foundation for single-account setups
# ========================================================
# Perfect for solo founders, small teams, or single-project accounts.
# No Organization, no OUs - Identity Center + IPAM + Network for SSO, IP management, and VPC.
#
# What you get:
# - Identity Center with groups and permission sets for SSO access
# - IPAM with hierarchical IPv4 and IPv6 pools (global → regional) for VPC allocation
# - VPC network with public/private subnets and NAT gateway
#
# After apply:
# - SSO groups and permission sets are ready in Identity Center
# - VPC is created with IPAM-allocated CIDR
# - Ready to deploy workloads to the VPC
#
# Note: Account assignments require manual creation outside this Foundation
# since there's no Organization to resolve account references. Create them
# directly with ssoadmin.aws.m.upbound.io/v1beta1 AccountAssignment resources.

apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Foundation
metadata:
  name: my-foundation
  namespace: default
spec:
  managementPolicies: ["*"]

  aws:
    providerConfig: default
    region: us-east-1

  tags:
    managed-by: crossplane

  # No organization, no OUs, no accounts needed for single-account setup

  # ---------------------------------------------------------------------------
  # Identity Center
  # ---------------------------------------------------------------------------
  # Centralized SSO access management. Get identityStoreId and instanceArn
  # from AWS SSO console: IAM Identity Center > Settings.

  identityCenter:
    region: us-east-1
    identityStoreId: d-1234567890        # From AWS SSO console
    instanceArn: arn:aws:sso:::instance/ssoins-abcdef0123456789

    # Groups for access control
    groups:
      - name: Administrators
        description: Full administrative access

      - name: Developers
        description: Development access for building and deploying

      - name: ReadOnly
        description: Read-only access for viewing resources

    # Permission sets define what access each group gets
    # Note: assignToAccounts not used here since there's no Organization.
    # Create AccountAssignment resources separately to assign these
    # permission sets to your account.
    permissionSets:
      - name: AdministratorAccess
        description: Full administrator access
        sessionDuration: PT4H
        managedPolicies:
          - arn:aws:iam::aws:policy/AdministratorAccess

      - name: PowerUserAccess
        description: Developer access without IAM management
        sessionDuration: PT8H
        managedPolicies:
          - arn:aws:iam::aws:policy/PowerUserAccess

      - name: ViewOnlyAccess
        description: Read-only access for review
        sessionDuration: PT1H
        managedPolicies:
          - arn:aws:iam::aws:policy/ViewOnlyAccess

  # ---------------------------------------------------------------------------
  # IPAM - Hierarchical Dual-Stack IP Address Management
  # ---------------------------------------------------------------------------
  # IP Address Manager with global → regional pool hierarchy for dual-stack VPCs.
  #
  # Pool hierarchy:
  #   ipv4-global (10.0.0.0/8)
  #   └── ipv4-us-east-1 (10.0.0.0/12) ← allocate VPCs from here
  #
  #   ipv6-ula-global (/40)
  #   └── ipv6-ula-us-east-1 (/44) ← allocate VPCs from here
  #
  #   ipv6-gua-us-east-1 ← Amazon-provided public IPv6
  #
  # After apply, use Network Allocation XRDs to allocate from regional pools.

  ipam:
    region: us-east-1
    operatingRegions:
      - us-east-1

    pools:
      # ==========================================================================
      # IPv4 Pools - Global → Regional hierarchy
      # ==========================================================================
      ipv4:
        # Global pool - top of hierarchy
        - name: ipv4-global
          cidr: 10.0.0.0/8  # 16 million addresses
          allocations:
            netmaskLength:
              default: 12   # Carve /12 per region
          description: Global IPv4 pool

        # Regional pool - allocate VPCs from here
        - name: ipv4-us-east-1
          sourcePoolRef: ipv4-global
          locale: us-east-1
          cidr: 10.0.0.0/12  # 10.0.0.0 - 10.15.255.255
          allocations:
            netmaskLength:
              default: 16   # /16 per VPC (65k IPs)
              min: 16
              max: 24
          description: Regional IPv4 pool for us-east-1 VPCs

      # ==========================================================================
      # IPv6 Pools - ULA (private) and GUA (public)
      # ==========================================================================
      ipv6:
        # ULA pools - Private IPv6 (fd00::/8), not internet-routable
        # Use for internal services, databases, service mesh
        ula:
          # Global ULA pool
          - name: ipv6-ula-global
            netmaskLength: 40  # AWS assigns from fd00::/8
            allocations:
              netmaskLength:
                default: 44   # Carve /44 per region
            description: Global ULA IPv6 pool

          # Regional ULA pool - allocate VPCs from here
          - name: ipv6-ula-us-east-1
            sourcePoolRef: ipv6-ula-global
            locale: us-east-1
            netmaskLength: 44
            allocations:
              netmaskLength:
                default: 48   # /48 per VPC (65k subnets)
                min: 48
                max: 56
            description: Regional ULA IPv6 for us-east-1 VPCs

        # GUA pools - Amazon-provided public IPv6
        # Internet-routable, use for public-facing workloads
        gua:
          - name: ipv6-gua-us-east-1
            locale: us-east-1
            netmaskLength: 52  # AWS provisions /52
            publicIpSource: amazon
            awsService: ec2
            allocations:
              netmaskLength:
                default: 56   # /56 per VPC (256 /64 subnets)
                min: 52
                max: 60
            description: Public IPv6 pool (Amazon GUA) for internet-facing workloads

  # ---------------------------------------------------------------------------
  # Network - VPC with IPAM allocation
  # ---------------------------------------------------------------------------
  # For single-account setups, omit `account` to use spec.aws.providerConfig.
  # The network allocates its CIDR from the regional IPAM pool.
  networks:
    - name: main
      # No account = uses management account (spec.aws.providerConfig)
      region: us-east-1
      ipam:
        ipv4:
          poolRef: ipv4-us-east-1    # Reference pool by name
          netmaskLength: 16
      subnetLayout:
        availabilityZones: [a, b]    # 2 AZs for cost savings
        public:
          enabled: true
          netmaskLength: 24
        private:
          enabled: true
          netmaskLength: 20
      nat:
        enabled: true
        strategy: SingleAz           # Single NAT for cost savings
      tags:
        environment: development
